### PR TITLE
add tidio widget

### PR DESCRIPTION
**Pull request by huangj1e**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:
- [x] Add Tidio Widget

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This package can help you add Tidio instant messaging widgets to evershop

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
image

### CODE REVIEW

**Comment by treoden** [comment]
Hi @huangj1e ,

Thanks for this great widget. Can I suggest to publish it as a npm package and I am willing to list it on our extension page?
https://evershop.io/extensions

Thanks

**Comment by huangj1e** [comment]
Yes, please sign my name（huangj1e）, thank you

**Comment by huangj1e** [comment]
I will add more widget of the instant messaging platform later

**Comment by treoden** [comment]
> Yes, please sign my name（huangj1e）, thank you

Hi @huangj1e ,

I will not able to publish an npm package under your name, I will need you to do it. 
https://docs.npmjs.com/creating-and-publishing-scoped-public-packages

You can share me the package name later and I will take care of listing it on our website 

Thanks

**Comment by huangj1e** [comment]
is done 
 https://www.npmjs.com/package/evershop_tidio_widget

**Comment by huangj1e** [comment]
https://www.npmjs.com/package/evershop_tawk_widget

This is another chat component

**Comment by treoden** [comment]
Hi @huangj1e ,

Both extensions are added to our website: https://evershop.io/extensions

Thanks

**Pull request closed without merging**
